version: '3'
services:
  apiservice:
    container_name: apiService
    build: .
    ports:
      - 8080:80
      - 8081:443
    environment:
      ASPNETCORE_URLS: "http://+;https://+"
      ASPNETCORE_HTTPS_PORT: 8081
      ASPNETCORE_ENVIRONMENT: Development
    restart: on-failure
    volumes:
      - ${APPDATA}\microsoft\UserSecrets\:/root/.microsoft/usersecrets
      - ${USERPROFILE}\.aspnet\https:/root/.aspnet/https/