version: '3'
services:
  apiservice:
    container_name: apiService
    build: .
    ports:
      - 8080:5000
      - 8081:5001
    environment:
      ASPNETCORE_URLS: "http://+:5000;https://+:5001"
      ASPNETCORE_HTTPS_PORT: 8081
      ASPNETCORE_ENVIRONMENT: Development
    restart: on-failure
    volumes:
      - ${APPDATA}\microsoft\UserSecrets\:/root/.microsoft/usersecrets
      - ${USERPROFILE}\.aspnet\https:/root/.aspnet/https/